### Create Profile
POST localhost:8080/profile/restration
Content-Type: application/json

{
  "name": "G'ani",
  "surname": "G'aniyev",
  "phone": "222222222",
  "password": "2222",
  "role": "ROLE_MANAGER"
}