### Create Task
POST localhost:8080/task
Content-Type: application/json
Authorization: Basic MjIyMjIyMjIyOjIyMjI=

{
  "title": "Kursga",
  "content": "Kursga borish kerak"
}


### Get all
GET localhost:8080/task


### Get all task
GET localhost:8080/task/my
Authorization: Basic OTMxMDUxNzM5OjEyMzQ=


### Update By Id
PUT localhost:8080/task/ff808081930b90ae01930b91a0210000
Content-Type: application/json
Authorization: Basic OTMxMDUxNzM5OjEyMzQ=

{
  "title": "Relax",
  "content": "Sartoroshga borish kerak"
}


### Delete Task by id
DELETE localhost:8080/task/ff808081930b90ae01930b93f9a70001
Authorization: Basic OTMxMDUxNzM5OjEyMzQ=


### Delete Task By Admin
DELETE localhost:8080/task/ff808081930b90ae01930b93f9a70001/admin
Authorization: Basic OTMxMDUxNzM5OjEyMzQ=