### Create Task
POST localhost:8080/task
Content-Type: application/json
Authorization: Basic bWF6Z2k6MTIzNA==

{
  "title": "Sartarosh",
  "content": "Sartoroshga borish kerak"
}


### Get all
GET localhost:8080/task


### Delete Task by id
DELETE localhost:8080/task/dbebcd3d-7bb5-439e-8892-178205dedc4d
Authorization: Basic bWF6Z2k6MTIzNA==